import type {
  ProjectEntity,
  SourceEntity,
  StageDefinition,
} from './types';

const SKILL_ROOT = '.agent/skills';

export function getSourceStageDefinitions(source: SourceEntity): StageDefinition[] {
  return [
    {
      stageId: 'source-planning',
      label: '기획 생성',
      description: 'planning.md와 source 메타데이터를 검수 가능한 초안으로 만듭니다.',
      category: 'codex',
      requiredInputs: ['source.json'],
      allowedOutputs: ['source.json', 'planning.md'],
      canRun: true,
      canApprove: true,
      nextStage: 'approved',
      routeBackStage: 'ingested',
      skillPath: `${SKILL_ROOT}/content_planner/SKILL.md`,
    },
    {
      stageId: 'source-approve',
      label: '후보 승인',
      description: '메인 카드, 단독 후속 카드, 즉시 생성 큐를 확정합니다.',
      category: 'manual',
      requiredInputs: ['source.json', 'planning.md'],
      allowedOutputs: ['source.json'],
      canRun: true,
      canApprove: true,
      nextStage: 'approved',
      routeBackStage: 'analyzed',
    },
    {
      stageId: 'spawn-approved',
      label: '프로젝트 생성',
      description: '승인된 후보를 실제 프로젝트 폴더로 생성합니다.',
      category: 'command',
      requiredInputs: ['source.json', 'planning.md'],
      allowedOutputs: [],
      canRun: source.status === 'approved' && source.approvedCandidateIds.length > 0,
      canApprove: false,
      nextStage: 'spawned',
      routeBackStage: 'approved',
    },
  ];
}

export function getProjectStageDefinitions(project: ProjectEntity): StageDefinition[] {
  const stage = project.stage;
  const slidePlanApproved = project.approvalStatus === 'approved';

  return [
    {
      stageId: 'research',
      label: '리서치',
      description: '근거를 보강하고 research_brief.md를 준비합니다.',
      category: 'codex',
      requiredInputs: ['project.json'],
      allowedOutputs: ['research_brief.md'],
      canRun: project.requiresResearchBrief,
      canApprove: true,
      nextStage: 'planning',
      routeBackStage: 'researching',
      skillPath: `${SKILL_ROOT}/content_researcher/SKILL.md`,
    },
    {
      stageId: 'plan',
      label: '플래닝',
      description: '승인 가능한 slide_plan.md 초안을 정리합니다.',
      category: 'codex',
      requiredInputs: ['project.json'],
      allowedOutputs: ['slide_plan.md'],
      canRun: ['researching', 'planning', 'awaiting_plan_approval'].includes(stage),
      canApprove: true,
      nextStage: 'awaiting_plan_approval',
      routeBackStage: 'planning',
      skillPath: `${SKILL_ROOT}/content_planner/SKILL.md`,
    },
    {
      stageId: 'approve-slide-plan',
      label: '기획 승인',
      description: 'slide plan을 승인하고 에디터용 문서를 시드합니다.',
      category: 'manual',
      requiredInputs: ['project.json', 'slide_plan.md'],
      allowedOutputs: ['project.json', 'approvals.json', 'carousel_draft.md', 'handoff_brief.md'],
      canRun: true,
      canApprove: true,
      nextStage: 'plan_approved',
      routeBackStage: 'planning',
    },
    {
      stageId: 'edit',
      label: '에디터',
      description: 'carousel_draft.md와 handoff_brief.md를 작성합니다.',
      category: 'codex',
      requiredInputs: ['project.json', 'slide_plan.md'],
      allowedOutputs: ['carousel_draft.md', 'handoff_brief.md'],
      canRun: slidePlanApproved || stage === 'plan_approved' || stage === 'writing',
      canApprove: true,
      nextStage: 'designing',
      routeBackStage: 'writing',
      skillPath: `${SKILL_ROOT}/content_editor/SKILL.md`,
    },
    {
      stageId: 'design',
      label: '디자인',
      description: 'carousel.json을 만들고 시각 자산 참조를 정리합니다.',
      category: 'codex',
      requiredInputs: ['project.json', 'carousel_draft.md', 'handoff_brief.md'],
      allowedOutputs: ['carousel.json'],
      canRun: slidePlanApproved || ['designing', 'qa'].includes(stage),
      canApprove: true,
      nextStage: 'designing',
      routeBackStage: 'writing',
      skillPath: `${SKILL_ROOT}/slide_designer/SKILL.md`,
    },
    {
      stageId: 'render-preview',
      label: '미리보기 렌더',
      description: '현재 carousel.json 기준으로 미리보기 이미지를 렌더합니다.',
      category: 'command',
      requiredInputs: ['carousel.json'],
      allowedOutputs: ['renders/current'],
      canRun: Boolean(project.paths.carouselJson),
      canApprove: true,
      nextStage: 'qa',
      routeBackStage: 'designing',
    },
    {
      stageId: 'qa',
      label: 'QA',
      description: 'qa_report.md와 품질 상태를 업데이트합니다.',
      category: 'codex',
      requiredInputs: ['project.json', 'carousel.json'],
      allowedOutputs: ['qa_report.md', 'project.json'],
      canRun: ['qa', 'designing', 'done'].includes(stage),
      canApprove: true,
      nextStage: 'done',
      routeBackStage: 'designing',
      skillPath: `${SKILL_ROOT}/content_qa/SKILL.md`,
    },
  ];
}
